# Model Building - Support Vector Machine

This notebook implements the model building for my thesis comparing different supervised machine learning techniques (logistic regression, random forests, support vector machines and neural networks). The main focus surrounds when each method results in better performance as measured by discrimination (AUC) and calibration (calibration plots). This project considers various factors including the number of features, number of datapoints and 'predictor strength'. This notebook fits a Support Vector Machine to a small number of variables and outputs prediction and results to a pandas dataframe, where model evaliation and results will be undertaken in a following notebook.

In [1]:
import glob
import numpy as np
import os
import pandas as pd
import sklearn

from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, auc
from sklearn.model_selection import StratifiedKFold, train_test_split
from scipy.stats import loguniform, uniform, randint

np.random.seed(21)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
def hyperparameter_randomiser_svm(c_range,
                                  gamma_range,
                                  c_dist = "log_uniform",
                                  gamma_dist = "log_uniform",
                                  prints = False):
    '''
    Returns the best hyperparameters from given ranges using a random search algorithm:
    c_range: Upper and lower bounds of the c distribution range as a list
    gamma_range: Upper and lower bounds of the gamma distribution range as a list
    c_dist: An argument specifying whether the distribution is drawn from a uniform or log uniform distribution
            arguments: "log_uniform", "uniform"
    gamma_dist: An argument specifying whether the distribution is drawn from a uniform or log uniform distribution
                arguments: "log_uniform", "uniform"
    prints: An option to facilitate the printing of the randomly selected hyperparameters at each search.
    '''
    if c_dist=="log_uniform":
        c = loguniform(c_range[0], c_range[1]).rvs(1).item()
    elif c_dist=="uniform":
        c = uniform(c_range[0], c_range[1]).rvs(1).item()
    else:
        raise Exception("Please provide a valid c distribution.")
    if gamma_dist=="log_uniform":
        gamma = loguniform(gamma_range[0], gamma_range[1]).rvs(1).item()
    elif gamma_dist=="uniform":
        gamma = uniform(gamma_range[0], gamma_range[1]).rvs(1).item()
    else:
        raise Exception("Please provide a valid gamma distribution.")
    if prints == True:
        print("c:", c)
        print("gamma:", gamma)
    return c, gamma

In [3]:
def build_model_svm(ce, gamma):
    SVM = SVC(C = ce, gamma = gamma, kernel = 'rbf', probability = True)
    return SVM

In [4]:
def hyp_tuner_svm(cee_range,
                  gam_range,
                  X_train, 
                  y_train, 
                  X_test, 
                  y_test,
                  cv_folds = 5, 
                  random_search = 20):
    '''Returns the best hyperparameters from given ranges using a random search algorithm:
        c_range: Range of max depth of consituent decision trees
        gamma_range: Range of max features in each split
        X_train: The training dataset (as a pandas dataframe) features
        y_train: The training dataset (as a pandas dataframe) labels
        X_test: The testing dataset (as a pandas dataframe) features
        y_test: The testing dataset (as a pandas dataframe) labels
        cv_folds: Number of folds of cross validation (default 5)
        random_search: how many random searches are performed (default 20)
        '''
    cv = StratifiedKFold(n_splits = cv_folds, shuffle = True, random_state = 21)
    cv.get_n_splits(X_train, y_train)
    #splitting the dataset for k-fold
    c_list, gamma_list = [], []
    auc_dict = dict()
    #creating dictionaries and lists that store information on hyperparameters and aucs
    for i in range(random_search):
        print("Running search {counter} out of {maxi}".format(counter = str(i+1), maxi = str(random_search)))
        #randomly selecting hyperparameters and storing them
        cee, gam = hyperparameter_randomiser_svm(c_range = cee_range,
                                                 gamma_range = gam_range) 
        c_list.append(cee)
        gamma_list.append(gam)
        auc_dict[i] = []
        for train_index, test_index in cv.split(X_train, y_train):
            #cross validating
            model = build_model_svm(ce = cee,
                                    gamma = gam)
            X1_train, X1_valid = X_train.iloc[train_index], X_train.iloc[test_index]
            y1_train, y1_valid = y_train.iloc[train_index], y_train.iloc[test_index]
            model.fit(X1_train, y1_train)
            y1_pred = model.predict_proba(X1_valid)[:, 1]
            fpr, tpr, threshold = roc_curve(y1_valid, y1_pred)
            cauc = auc(fpr, tpr)
            auc_dict[i].append(cauc)
    #analysing results to find best hyperparameters
    hp_dict = {"c": c_list,
               "gamma": gamma_list}
    av_auc_dict = dict()
    for k, v in auc_dict.items():
        av_auc_dict[k] = sum(v)/len(v)
    opt_hyper = max(av_auc_dict, key = av_auc_dict.get)
    opt_c = hp_dict["c"][opt_hyper]
    opt_gamma = hp_dict["gamma"][opt_hyper]
    #building the model based on the whole training data based on optimal parameters
    opt_model = build_model_svm(ce = opt_c, 
                                gamma = opt_gamma)
    opt_model.fit(X_train, y_train)
    y_pred = opt_model.predict_proba(X_test)[:, 1]
    v_auc = roc_auc_score(y_test, y_pred)
    #sorting prediction df
    y_test_df = pd.DataFrame(y_test)
    pred_df = pd.DataFrame(y_pred)
    pred_df['index'] = y_test.index
    pred_df.set_index('index', inplace = True)
    pred_df.rename(columns = {0: "prob"}, inplace = True)
    df = pred_df.join(y_test_df, how = 'left')
    print("The best hyperparameters were:")
    print("c:", opt_c)
    print("gamma:", opt_gamma)
    y_pred2 = opt_model.predict(X_test)
    print(confusion_matrix(y_test, y_pred2))
    opt_svm = opt_model
    
    return df, v_auc

In [5]:
def min_max_scaling(df):
    # copy the dataframe
    df_norm = df.copy()
    # apply min-max scaling
    for column in df_norm.columns:
        df_norm[column] = (df_norm[column] - df_norm[column].min()) / (df_norm[column].max() - df_norm[column].min())
        
    return df_norm
# credit:
# https://towardsdatascience.com/data-normalization-with-pandas-and-scikit-learn-7c1cc6ed6475#:~:text=maximum%20absolute%20scaling.-,The%20min%2Dmax%20feature%20scaling,max()%20methods.

In [6]:
current_wd = os.getcwd()
base_wd = current_wd
base_wd = base_wd.replace("\\", "/")
path = base_wd + "/data/bootstraps"
os.chdir(path)
all_filenames = [i for i in glob.glob('*.{}'.format('csv'))]

In [7]:
%%time
#fitting support vector machines to each bootstrap
np.random.seed(21)
i = 0
dataframes = []
for filename in all_filenames:
    i += 1
    print(str(i) + " of " + str(len(all_filenames)))
    mf = pd.read_csv(filename)
    df = min_max_scaling(mf)
    X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(df.drop('deceased', axis = 1), 
                                                                        df['deceased'], test_size = 0.2, 
                                                                        random_state = 21, 
                                                                        stratify = df['deceased'])
    preds, sv_auc = hyp_tuner_svm(cee_range = [0.001, 1000],
                                  gam_range = [0.001, 1000],
                                  X_train = X_train,
                                  y_train = y_train,
                                  X_test = X_test,
                                  y_test = y_test,
                                  cv_folds = 3,
                                  random_search = 5)
    preds.reset_index(drop = True, inplace = True)
    dataframes.append(preds)
    print(sv_auc)
svm_predictions = pd.concat(dataframes, axis = 1)
svm_predictions.to_csv('./predictions/sv_predictions.csv', index = False)

1 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.9453166319420468
gamma: 152.12404587716756
[[823   2]
 [ 59  68]]
0.9598950131233595
2 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 179.71136701341393
gamma: 362.06540171441236
[[817   0]
 [ 60  75]]
0.9488598757876604
3 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 4.001433394614622
gamma: 245.49464966698156
[[820   1]
 [ 64  67]]
0.9524690611895753
4 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 23.266076729072953
gamma: 0.22503410581264216
[[

The best hyperparameters were:
c: 503.8276626568869
gamma: 0.032921337878991264
[[812   9]
 [110  21]]
0.8487322293609543
33 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 14.19361706080262
gamma: 21.544805142538237
[[782  34]
 [ 43  93]]
0.9032538566897347
34 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 2.514549321707827
gamma: 0.02746541422292303
[[824   0]
 [128   0]]
0.8409530491504855
35 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.5610521780053135
gamma: 179.3622354749524
[[820   0]
 [ 96  36]]
0.9473300073909832
36 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running s

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 197.1094981717769
gamma: 41.83988228910064
[[804  21]
 [ 39  88]]
0.9351944643283228
65 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.027094124033178537
gamma: 115.5384819123988
[[821   0]
 [131   0]]
0.947429591542617
66 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.016220420012901544
gamma: 363.49139629314476
[[813   0]
 [139   0]]
0.9509189696213509
67 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.7283610430775547
gamma: 337.3783671133212
[[813   0]
 [112  27]]
0.9461183820

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 51.40954622727737
gamma: 127.14983521593882
[[811  10]
 [ 48  83]]
0.9430037842511924
97 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0211321386529459
gamma: 0.11951907282075243
[[814   0]
 [138   0]]
0.835843748887227
98 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.12865853664543753
gamma: 25.294951713615788
[[822   0]
 [129   1]]
0.8887703537338575
99 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.14302570036986992
gamma: 147.42389536837712
[[823   0]
 [129   0]]
0.93832358

Running search 5 out of 5
The best hyperparameters were:
c: 79.81904713162766
gamma: 404.13624443790906
[[819   1]
 [ 64  68]]
0.9536123429416112
128 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 2.1194793146070205
gamma: 45.990902920427494
[[814  11]
 [ 54  73]]
0.900548795036984
129 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0020985920523385175
gamma: 286.7139628891868
[[822   0]
 [130   0]]
0.9511884708965002
130 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.6874051851879138
gamma: 471.0716831913715
[[821   0]
 [105  26]]
0.9447982817454045
131 of 999
Running search 1 out of 5
Running search 2 out of 5
Runni

[[818   0]
 [ 61  73]]
0.9587818851950517
159 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 17.567942025916853
gamma: 0.004457557966935623
[[822   0]
 [130   0]]
0.8512914093206064
160 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 34.7846569871432
gamma: 649.485468941996
[[813   0]
 [ 81  58]]
0.9340394842797348
161 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.002799652544649319
gamma: 159.46361542156873
[[823   0]
 [129   0]]
0.9359688038656079
162 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:


Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 85.81657560007487
gamma: 146.51363674985265
[[816  10]
 [ 56  70]]
0.949959644874899
191 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 2.5284254160402395
gamma: 278.4846521349215
[[816   0]
 [ 53  83]]
0.9521788494809689
192 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.7894148448561567
gamma: 231.62290182743897
[[816   0]
 [ 82  54]]
0.940297902249135
193 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.17555355464081418
gamma: 52.71636367083903
[[820   0]
 [125   7]]
0.9074002217

Running search 5 out of 5
The best hyperparameters were:
c: 366.7857832011575
gamma: 25.068090901147286
[[790  23]
 [ 42  97]]
0.8828922102170661
222 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 221.59028534996435
gamma: 125.45732558430481
[[812  11]
 [ 48  81]]
0.9367882675407613
223 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 294.5935456826384
gamma: 4.3473350240205555
[[795  24]
 [ 54  79]]
0.8748795064584538
224 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 1.1986528904086076
gamma: 27.270336645965216
[[808  13]
 [ 63  68]]
0.9000567172783144
225 of 999
Running search 1 out of 5
Running search 2 out of 5
Runnin

[[824   0]
 [128   0]]
0.9542342991504854
253 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.006657540845627832
gamma: 163.41917141070354
[[826   0]
 [126   0]]
0.9725777316576347
254 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 74.68859382182924
gamma: 256.66465226128145
[[824   5]
 [ 74  49]]
0.9278688203046083
255 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 566.3746437442048
gamma: 0.05761885306955699
[[800  20]
 [ 76  56]]
0.8531042128603105
256 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:

Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 147.44592903165264
gamma: 47.26428194159057
[[795  22]
 [ 52  83]]
0.8865950405730089
285 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 5.198434568083945
gamma: 0.012741567361275566
[[812   0]
 [140   0]]
0.8478008444757212
286 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.19070194077766967
gamma: 0.11996731252999264
[[824   0]
 [128   0]]
0.8229530112257283
287 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 25.347622781582785
gamma: 786.2147412247325
[[810   0]
 [ 61  81]]
0.9295252999478352
288 of 999
Run

The best hyperparameters were:
c: 689.1081534202593
gamma: 245.58842337810208
[[812   1]
 [ 56  83]]
0.9627014255754068
316 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.03954263058007964
gamma: 0.10367500831949383
[[823   0]
 [129   0]]
0.8797743178200382
317 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0037750297678126815
gamma: 106.76970787071613
[[817   0]
 [135   0]]
0.9467518926515255
318 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 38.622338021712686
gamma: 246.83504834917707
[[816   1]
 [ 62  73]]
0.9440727140849541
319 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5


Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 2.1350320539824486
gamma: 430.01247160712467
[[829   0]
 [ 64  59]]
0.9297370717977385
348 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.03633892126236002
gamma: 169.41691771563396
[[824   0]
 [128   0]]
0.9460330703883495
349 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0249381067494501
gamma: 115.29946264488531
[[824   0]
 [128   0]]
0.9048325621966018
350 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.004045818734360698
gamma: 0.003853130555455684
[[818   0]
 [134   0]]
0.8

Running search 5 out of 5
The best hyperparameters were:
c: 98.30033347375684
gamma: 181.64328015689682
[[820   3]
 [ 47  82]]
0.944992323414997
379 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 894.5948974290144
gamma: 175.51055464599307
[[822   2]
 [ 65  63]]
0.9541394872572816
380 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 47.52049676734867
gamma: 155.17178699571008
[[820   3]
 [ 56  73]]
0.9517269961475787
381 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 49.32538811869342
gamma: 0.03190825743693909
[[816   0]
 [136   0]]
0.8573114907727797
382 of 999
Running search 1 out of 5
Running search 2 out of 5
Running 

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 83.09083948715191
gamma: 109.93096813695458
[[800  10]
 [ 54  88]]
0.9445922448269866
411 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 72.8792919169488
gamma: 0.0021376920542357973
[[823   0]
 [129   0]]
0.8216583307430747
412 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 230.96734513341903
gamma: 176.23258432014123
[[808   4]
 [ 62  78]]
0.9389778325123155
413 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 2.453594249002226
gamma: 54.35928021732102
[[814   8]
 [ 54  76]]
0.90466966

The best hyperparameters were:
c: 0.06865090966773872
gamma: 0.0013665444068258073
[[826   0]
 [126   0]]
0.8115799992313311
442 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.4276305788638817
gamma: 34.8537595519765
[[809   7]
 [106  30]]
0.9051686851211074
443 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.9322882066763285
gamma: 213.9219214874341
[[813   2]
 [ 57  80]]
0.9516725628050693
444 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 6.857720055927425
gamma: 745.8990233116501
[[816   0]
 [ 52  84]]
0.9528952205882353
445 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Runni

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 123.11043148350167
gamma: 101.77920699275965
[[799  15]
 [ 54  84]]
0.9275006231527971
474 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 718.0719847980344
gamma: 272.55473167618857
[[821   0]
 [ 58  73]]
0.9623434463649803
475 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.003012266768286823
gamma: 222.2941104497861
[[818   0]
 [134   0]]
0.9593657628726782
476 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 94.79452767339208
gamma: 40.05606488794284
[[783  31]
 [ 41  97]]
0.89288893

The best hyperparameters were:
c: 114.9763692668293
gamma: 0.14404356322045558
[[805  18]
 [ 79  50]]
0.8241261408912374
505 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 1.4698084413970267
gamma: 30.024531152624927
[[806  16]
 [ 66  64]]
0.8812371326969867
506 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 13.26346903502587
gamma: 180.20538270893059
[[807   3]
 [ 65  77]]
0.9414101895322552
507 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.027131578812581107
gamma: 51.69426696888362
[[822   0]
 [130   0]]
0.8968556990454801
508 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Runn

[[824   0]
 [128   0]]
0.9456633040048543
536 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 4.824495587396699
gamma: 0.04840089645106202
[[825   0]
 [127   0]]
0.8540109759007397
537 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.7402710408288541
gamma: 554.195678457888
[[827   0]
 [102  23]]
0.9432696493349457
538 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 2.8511783864249574
gamma: 263.75577897064056
[[821   3]
 [ 55  73]]
0.9609280188106796
539 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c:

Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 5.91194703794782
gamma: 314.33917085217183
[[827   0]
 [ 48  77]]
0.9576783555018138
568 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0049063124363176525
gamma: 267.48066657738065
[[817   0]
 [135   0]]
0.9353823836075977
569 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.004550466529059056
gamma: 360.8777115892869
[[818   0]
 [134   0]]
0.9430080648104222
570 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 588.4931611477439
gamma: 126.7740264595488
[[817   6]
 [ 60  69]]
0.9302231390168318
571 of 999
Runn

[[814   0]
 [ 69  69]]
0.9455854075419292
599 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0034433623208088558
gamma: 11.331919479720868
[[820   0]
 [132   0]]
0.8134146341463413
600 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 59.12369085356495
gamma: 896.086103250205
[[822   0]
 [ 51  79]]
0.9399307505146922
601 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.012176602819545084
gamma: 19.059011069848005
[[822   0]
 [130   0]]
0.869127830806663
602 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 25.24202924456329
gamma: 613.1162830891818
[[823   0]
 [ 57  72]]
0.9272561153654149
631 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 301.2825049653281
gamma: 65.7854869779206
[[796  19]
 [ 51  86]]
0.9154896780260624
632 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.857452260482546
gamma: 81.81904842992684
[[818   6]
 [ 73  55]]
0.9315458131067962
633 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.006824621053577883
gamma: 23.944526663380135
[[808   0]
 [144   0]]
0.86575220022

The best hyperparameters were:
c: 943.0102420443823
gamma: 451.04983147369296
[[814   0]
 [ 63  75]]
0.9499652814870206
662 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.08149770212849343
gamma: 41.22689681488043
[[814   0]
 [138   0]]
0.9136844354235657
663 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.1946202605995832
gamma: 180.07405411655466
[[812   0]
 [140   0]]
0.9654380717804364
664 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.030472203922543885
gamma: 0.09151967011463391
[[815   0]
 [137   0]]
0.8517307778424611
665 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Ru

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.3132740756642281
gamma: 201.5036987454987
[[824   0]
 [124   4]]
0.9500056887135923
694 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.26639375704961565
gamma: 776.8219550380135
[[825   0]
 [125   2]]
0.957780959198282
695 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.03324776403954028
gamma: 121.71966519951661
[[832   0]
 [120   0]]
0.9268229166666666
696 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0014968211816535893
gamma: 0.0065530408145971514
[[823   0]
 [129   0]]
0.7

Running search 5 out of 5
The best hyperparameters were:
c: 0.001594972063099968
gamma: 107.35638901316406
[[817   0]
 [135   0]]
0.9258443265787206
725 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.03332655998239731
gamma: 55.627774798976255
[[822   0]
 [130   0]]
0.9128298708590679
726 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 2.63461360225923
gamma: 0.05312842632005829
[[815   0]
 [137   0]]
0.865666562178138
727 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 7.025920194518713
gamma: 0.02242725498818625
[[810   0]
 [142   0]]
0.8219309685272127
728 of 999
Running search 1 out of 5
Running search 2 out of 5
Run

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0026338158898029157
gamma: 56.40295821373087
[[808   0]
 [144   0]]
0.8746476210121011
757 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 32.92243614997256
gamma: 932.0438716135455
[[825   0]
 [ 60  67]]
0.9399856836077308
758 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.03382614130039365
gamma: 707.0653137221202
[[812   0]
 [140   0]]
0.9402797325826883
759 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.8658376176188007
gamma: 0.24219821381324788
[[818   0]
 [134   0]]
0.83535

Running search 5 out of 5
The best hyperparameters were:
c: 0.002903276881505406
gamma: 73.12067881095456
[[821   0]
 [131   0]]
0.9049474202936281
788 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.026044719908210685
gamma: 230.11492652078203
[[811   0]
 [141   0]]
0.9370840657274532
789 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 3.1563609770212984
gamma: 39.70543740762991
[[795  26]
 [ 49  82]]
0.893064685591022
790 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.06919824343267492
gamma: 51.61001188520173
[[817   0]
 [135   0]]
0.8966589600616529
791 of 999
Running search 1 out of 5
Running search 2 out of 5
Run

[[818   0]
 [134   0]]
0.9399427070028828
819 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.17737243567803315
gamma: 86.67603500431895
[[815   0]
 [137   0]]
0.9457435851506872
820 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 10.79740943981228
gamma: 153.76632148461027
[[819   5]
 [ 61  67]]
0.9566899271844659
821 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 6.411885292751897
gamma: 0.06908111215746413
[[820   0]
 [132   0]]
0.8358739837398375
822 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c

Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 147.74156270030412
gamma: 12.718469200067604
[[793  33]
 [ 45  81]]
0.8638302778738615
851 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.19240640294576744
gamma: 300.9047417271667
[[820   0]
 [132   0]]
0.9568043237250554
852 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 457.1639148201465
gamma: 211.33868579623254
[[815   6]
 [ 50  81]]
0.9561696311517326
853 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 108.24867782170651
gamma: 1.6211025028193444
[[808  20]
 [ 77  47]]
0.8252103786816269
854 of 999
Runni

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 236.99717761051713
gamma: 0.002876543652010474
[[816   0]
 [136   0]]
0.7979112600922722
883 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.011623907421646183
gamma: 54.84439299504926
[[813   0]
 [139   0]]
0.9323935685400018
884 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 9.921434753544633
gamma: 132.8940808148305
[[817   6]
 [ 51  78]]
0.9567285503028248
885 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 478.6517115015831
gamma: 0.010023374371268087
[[820   4]
 [115  13]]
0.8543

Running search 5 out of 5
The best hyperparameters were:
c: 2.532878073807745
gamma: 418.32494625348346
[[821   0]
 [ 54  77]]
0.9520831977387472
914 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.15968870966240759
gamma: 123.43894915594586
[[821   0]
 [131   0]]
0.9291777854227297
915 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 8.565500668827864
gamma: 0.004149299054463459
[[819   0]
 [133   0]]
0.8679207175447778
916 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 353.965570500726
gamma: 0.004318070813058466
[[817   0]
 [135   0]]
0.8392764857881138
917 of 999
Running search 1 out of 5
Running search 2 out of 5
Run

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.10428783384967218
gamma: 292.18344649975495
[[824   0]
 [128   0]]
0.9459098149271845
946 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 426.12942577711556
gamma: 472.7944525003953
[[816   0]
 [ 58  78]]
0.9546118079584776
947 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.032750922533399764
gamma: 440.30747472152484
[[824   0]
 [128   0]]
0.9447815533980581
948 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.0013888020793214673
gamma: 260.9082585791644
[[825   0]
 [127   0]]
0.87

Running search 5 out of 5
The best hyperparameters were:
c: 0.01100355718038945
gamma: 0.001753922910209812
[[821   0]
 [131   0]]
0.7592026108543852
977 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 0.12413496002935116
gamma: 75.33984005670852
[[816   0]
 [136   0]]
0.9239024653979239
978 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 3.9676371254555316
gamma: 117.47539100964373
[[820  10]
 [ 56  66]]
0.9360211337151885
979 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
c: 415.81755854994975
gamma: 115.78923664621301
[[812   9]
 [ 52  79]]
0.9391358518284348
980 of 999
Running search 1 out of 5
Running search 2 out of 5
R