# Model Building - Random Forest

This notebook implements the model building for my thesis comparing different supervised machine learning techniques (logistic regression, random forests, support vector machines and neural networks). The main focus surrounds when each method results in better performance as measured by discrimination (AUC) and calibration (calibration plots). This project considers various factors including the number of features, number of datapoints and 'predictor strength'. This notebook fits random forests to a small number of variables and outputs prediction and results to a pandas dataframe, where model evaliation and results will be undertaken in a following notebook.

In [1]:
import glob
import numpy as np
import os
import pandas as pd
import sklearn

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, auc
from sklearn.model_selection import StratifiedKFold, train_test_split
from scipy.stats import loguniform, uniform, randint

np.random.seed(21)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
def hyperparameter_randomiser_rf(max_depth_range,
                                 max_features_range,
                                 min_leaf_range,
                                 n_trees_range,
                                 prints = False):
    '''
    Returns the best hyperparameters from given ranges using a random search algorithm 
    (all searches use uniform distribution):
    max_depth_range: Range of max_depth
    max_features_range: Range of maximum features per split
    min_leaf_range: Range of minimum data points per leaf node
    n_trees_range: Range of number of trees in a constituent random forest
    prints: An option to facilitate the printing of the randomly selected hyperparameters at each search.
    '''
    max_depth = randint(max_depth_range[0], max_depth_range[1] + 1).rvs(1).item()
    max_features = randint(max_features_range[0], max_features_range[1] + 1).rvs(1).item()
    min_leaf = randint(min_leaf_range[0], min_leaf_range[1] + 1).rvs(1).item()
    n_trees = randint(n_trees_range[0], n_trees_range[1] + 1).rvs(1).item()
    if prints == True:
        print("max_depth:", max_depth)
        print("max_features:", max_features)
        print("min_leaf:", min_leaf)
        print("n_trees:", n_trees)
    return max_depth, max_features, min_leaf, n_trees

In [3]:
def build_model_rf(max_depth, max_features, min_leaf, n_trees):
    rf = RandomForestClassifier(n_estimators = n_trees, 
                                max_depth = max_depth, 
                                max_features = max_features,
                                min_samples_leaf = min_leaf)
    return rf

In [4]:
def hyp_tuner_rf(md_range, 
                 mf_range,
                 ml_range,
                 nt_range,
                 X_train, 
                 y_train, 
                 X_test, 
                 y_test,
                 cv_folds = 5, 
                 random_search = 20):
    '''Returns the best hyperparameters from given ranges using a random search algorithm:
        md_range: Range of max depth of consituent decision trees
        mf_range: Range of max features in each split
        X_train: The training dataset (as a pandas dataframe) features
        y_train: The training dataset (as a pandas dataframe) labels
        X_test: The testing dataset (as a pandas dataframe) features
        y_test: The testing dataset (as a pandas dataframe) labels
        cv_folds: Number of folds of cross validation (default 5)
        random_search: how many random searches are performed (default 20)
        '''
    cv = StratifiedKFold(n_splits = cv_folds, shuffle = True, random_state = 21)
    cv.get_n_splits(X_train, y_train)
    #splitting the dataset for k-fold
    md_list, mf_list, ml_list, nt_list = [], [], [], []
    auc_dict = dict()
    #creating dictionaries and lists that store information on hyperparameters and aucs
    for i in range(random_search):
        print("Running search {counter} out of {maxi}".format(counter = str(i+1), maxi = str(random_search)))
        #randomly selecting hyperparameters and storing them
        md, mf, ml, nt = hyperparameter_randomiser_rf(max_depth_range = md_range,
                                                      max_features_range = mf_range,
                                                      min_leaf_range = ml_range,
                                                      n_trees_range = nt_range) 
        md_list.append(md)
        mf_list.append(mf)
        ml_list.append(ml)
        nt_list.append(nt)
        auc_dict[i] = []
        for train_index, test_index in cv.split(X_train, y_train):
            #cross validating
            model = build_model_rf(max_depth = md,
                                   max_features = mf,
                                   min_leaf = ml,
                                   n_trees = nt)
            X1_train, X1_valid = X_train.iloc[train_index], X_train.iloc[test_index]
            y1_train, y1_valid = y_train.iloc[train_index], y_train.iloc[test_index]
            model.fit(X1_train, y1_train)
            y1_pred = model.predict_proba(X1_valid)[:, 1]
            fpr, tpr, threshold = roc_curve(y1_valid, y1_pred)
            cauc = auc(fpr, tpr)
            auc_dict[i].append(cauc)
    #analysing results to find best hyperparameters
    hp_dict = {"max_depth": md_list,
               "max_features": mf_list,
               "min_leaf": ml_list,
               "n_trees": nt_list}
    av_auc_dict = dict()
    for k, v in auc_dict.items():
        av_auc_dict[k] = sum(v)/len(v)
    opt_hyper = max(av_auc_dict, key = av_auc_dict.get)
    opt_md = hp_dict["max_depth"][opt_hyper]
    opt_mf = hp_dict["max_features"][opt_hyper]
    opt_ml = hp_dict["min_leaf"][opt_hyper]
    opt_nt = hp_dict["n_trees"][opt_hyper]
    #building the model based on the whole training data based on optimal parameters
    opt_model = build_model_rf(max_depth = opt_md, 
                               max_features = opt_mf,
                               min_leaf = opt_ml,
                               n_trees = opt_nt)
    opt_model.fit(X_train, y_train)
    y_pred = opt_model.predict_proba(X_test)[:, 1]
    v_auc = roc_auc_score(y_test, y_pred)
    #sorting prediction df
    y_test_df = pd.DataFrame(y_test)
    pred_df = pd.DataFrame(y_pred)
    pred_df['index'] = y_test.index
    pred_df.set_index('index', inplace = True)
    pred_df.rename(columns = {0: "prob"}, inplace = True)
    df = pred_df.join(y_test_df, how = 'left')
    print("The best hyperparameters were:")
    print("max_depth:", opt_md)
    print("max_features:", opt_mf)
    print("min_leaf:", opt_ml)
    print("n_trees:", opt_nt)
    y_pred2 = opt_model.predict(X_test)
    print(confusion_matrix(y_test, y_pred2))
    
    return df, v_auc

In [5]:
current_wd = os.getcwd()
base_wd = current_wd
base_wd = base_wd.replace("\\", "/")
path = base_wd + "/data/bootstraps"
os.chdir(path)
all_filenames = [i for i in glob.glob('*.{}'.format('csv'))]

In [6]:
%%time
#fitting random_forests to each bootstrap
np.random.seed(21)
i = 0
dataframes = []
for filename in all_filenames:
    i += 1
    print(str(i) + " of " + str(len(all_filenames)))
    mf = pd.read_csv(filename)
    X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(mf.drop('deceased', axis = 1), 
                                                                        mf['deceased'], test_size = 0.2, 
                                                                        random_state = 21, 
                                                                        stratify = mf['deceased'])
    preds, rf_auc = hyp_tuner_rf(md_range = [3, 8],
                                 mf_range = [1, 9],
                                 ml_range = [1, 5],
                                 nt_range = [100, 1000],
                                 X_train = X_train,
                                 y_train = y_train,
                                 X_test = X_test,
                                 y_test = y_test, 
                                 cv_folds = 3,
                                 random_search = 5)
    preds.reset_index(drop = True, inplace = True)
    dataframes.append(preds)
    print(rf_auc)
rf_predictions = pd.concat(dataframes, axis = 1)
rf_predictions.to_csv('./predictions/rf_predictions.csv', index = False)

1 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 4
min_leaf: 1
n_trees: 383
[[806  19]
 [ 76  51]]
0.917642567406347
2 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 4
n_trees: 975
[[806  11]
 [ 75  60]]
0.8965682941203137
3 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 1
n_trees: 558
[[798  23]
 [ 64  67]]
0.9109817667897091
4 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 9
min_leaf: 1
n_trees: 721
[[809  12]
 [ 74  57]]
0.9219440079590149
33 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 2
min_leaf: 3
n_trees: 968
[[795  21]
 [ 84  52]]
0.9185319348327566
34 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 6
min_leaf: 5
n_trees: 268
[[810  14]
 [ 70  58]]
0.9152855734223301
35 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 4
max_features: 6
min_leaf: 5
n_trees: 169
[[789  31]

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 1
n_trees: 305
[[805  18]
 [ 66  63]]
0.9378149519153787
64 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 2
n_trees: 755
[[809  16]
 [ 64  63]]
0.9343736578382248
65 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 5
min_leaf: 2
n_trees: 316
[[809  12]
 [ 76  55]]
0.8953240788091232
66 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 1
n_trees: 197
[[793  20]

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 4
n_trees: 404
[[803  16]
 [ 55  78]]
0.9449998622930954
95 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 2
n_trees: 619
[[800  12]
 [ 81  59]]
0.9270056298381422
96 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 6
min_leaf: 1
n_trees: 909
[[801  20]
 [ 69  62]]
0.9053472306161728
97 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 1
n_trees: 134
[[797  17]

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 2
n_trees: 900
[[825   1]
 [ 62  64]]
0.9343940966216995
126 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 9
min_leaf: 2
n_trees: 448
[[793  27]
 [ 74  58]]
0.8926182557280118
127 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 3
n_trees: 956
[[805  15]
 [ 72  60]]
0.9314486326681448
128 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 7
min_leaf: 2
n_trees: 303
[[816  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 5
min_leaf: 4
n_trees: 494
[[799  16]
 [ 69  68]]
0.9149164838117416
157 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 1
n_trees: 818
[[819   6]
 [ 67  60]]
0.923579098067287
158 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 2
n_trees: 183
[[812   6]
 [ 77  57]]
0.935435901178703
159 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 4
n_trees: 750
[[803  19

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 3
n_trees: 336
[[818  10]
 [ 65  59]]
0.931539270687237
188 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 2
n_trees: 564
[[792  14]
 [ 66  80]]
0.9199411944661613
189 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 1
n_trees: 575
[[807  18]
 [ 66  61]]
0.915075161059413
190 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 6
min_leaf: 3
n_trees: 816
[[803  23

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 4
n_trees: 333
[[807   6]
 [101  38]]
0.9064482731158247
219 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 1
n_trees: 277
[[799  16]
 [ 62  75]]
0.9333751287447942
220 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 4
n_trees: 863
[[809  17]
 [ 76  50]]
0.922095391829048
221 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 2
n_trees: 620
[[804   

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 5
min_leaf: 2
n_trees: 891
[[811  11]
 [ 78  52]]
0.9108459666853828
250 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 1
n_trees: 181
[[804  17]
 [ 67  64]]
0.9208096623927253
251 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 5
n_trees: 781
[[799  11]
 [ 73  69]]
0.939793079464441
252 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 2
min_leaf: 1
n_trees: 942
[[807  1

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 6
min_leaf: 4
n_trees: 927
[[809  11]
 [ 73  59]]
0.9177383592017738
281 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 3
min_leaf: 4
n_trees: 443
[[811  17]
 [ 77  47]]
0.8912751285647498
282 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 5
n_trees: 182
[[787  20]
 [ 77  68]]
0.9216211596803827
283 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 2
n_trees: 482
[[810  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 2
n_trees: 530
[[799  13]
 [ 81  59]]
0.9203377902885292
312 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 1
min_leaf: 2
n_trees: 672
[[812   3]
 [104  33]]
0.9127938739868344
313 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 1
n_trees: 535
[[796  17]
 [ 73  66]]
0.9117311316998061
314 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 3
n_trees: 462
[[817  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 3
n_trees: 429
[[803  17]
 [ 71  61]]
0.9167128603104213
343 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 1
n_trees: 762
[[815  10]
 [ 80  47]]
0.9301932712956336
344 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 2
n_trees: 879
[[810  11]
 [ 70  61]]
0.9341986592407323
345 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 1
n_trees: 1000
[[800 

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 4
min_leaf: 1
n_trees: 285
[[823   7]
 [ 72  50]]
0.9244519059845941
374 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 6
min_leaf: 1
n_trees: 909
[[811  10]
 [ 67  64]]
0.907653113406663
375 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 2
n_trees: 296
[[816   4]
 [ 86  46]]
0.9261086474501109
376 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 5
min_leaf: 3
n_trees: 695
[[806  1

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 5
min_leaf: 3
n_trees: 396
[[802  12]
 [ 76  62]]
0.92132250827903
405 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 6
min_leaf: 1
n_trees: 223
[[806   7]
 [ 57  82]]
0.9436583574468839
406 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 4
min_leaf: 2
n_trees: 572
[[812  12]
 [ 68  60]]
0.931811286407767
407 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 3
n_trees: 355
[[796  20]

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 1
n_trees: 553
[[819   4]
 [ 65  64]]
0.9362042819331808
436 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 9
min_leaf: 2
n_trees: 525
[[806  17]
 [ 75  54]]
0.910556010813153
437 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 9
min_leaf: 1
n_trees: 936
[[796  20]
 [ 73  63]]
0.9139228301614765
438 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 2
n_trees: 638
[[806  1

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 7
min_leaf: 2
n_trees: 205
[[799  21]
 [ 72  60]]
0.9048780487804878
467 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 7
min_leaf: 4
n_trees: 699
[[803  19]
 [ 69  61]]
0.929290660677522
468 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 4
n_trees: 424
[[801  20]
 [ 74  57]]
0.9079692424989075
469 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 5
min_leaf: 1
n_trees: 611
[[800  1

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 3
n_trees: 103
[[809  12]
 [ 82  49]]
0.9222043495643926
498 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 4
n_trees: 737
[[813   8]
 [ 71  60]]
0.9071882176827738
499 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 1
n_trees: 107
[[807  21]
 [ 65  59]]
0.9257538569424966
500 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 4
min_leaf: 1
n_trees: 660
[[810  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 6
min_leaf: 1
n_trees: 917
[[796  21]
 [ 66  69]]
0.8955347023890476
529 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 4
n_trees: 912
[[809  10]
 [ 58  75]]
0.9395650297905938
530 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 2
n_trees: 888
[[809  14]
 [ 70  59]]
0.9090301129352811
531 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 3
n_trees: 241
[[800  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 4
min_leaf: 5
n_trees: 520
[[806  12]
 [ 78  56]]
0.9306006641608584
560 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 7
min_leaf: 1
n_trees: 231
[[809  11]
 [ 75  57]]
0.9429878048780488
561 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 1
n_trees: 968
[[802  17]
 [ 65  68]]
0.9175319250507221
562 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 6
min_leaf: 1
n_trees: 646
[[809  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 1
n_trees: 953
[[807   9]
 [ 93  43]]
0.9310121107266437
591 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 1
n_trees: 613
[[805  15]
 [ 71  61]]
0.9087121212121213
592 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 5
min_leaf: 3
n_trees: 562
[[809  15]
 [ 70  58]]
0.8943416262135923
593 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 6
min_leaf: 3
n_trees: 704
[[786  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 2
n_trees: 539
[[799  26]
 [ 71  56]]
0.9221474588403722
622 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 1
n_trees: 956
[[815   9]
 [ 67  61]]
0.9235247269417475
623 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 4
n_trees: 897
[[801  21]
 [ 68  62]]
0.9160209620063635
624 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 4
n_trees: 625
[[802  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 9
min_leaf: 5
n_trees: 486
[[799  11]
 [ 89  53]]
0.8886280646844027
653 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 3
min_leaf: 3
n_trees: 906
[[806  13]
 [ 82  51]]
0.9029349931605569
654 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 2
n_trees: 193
[[799  17]
 [ 74  62]]
0.9391084558823529
655 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 1
n_trees: 102
[[806  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 7
min_leaf: 3
n_trees: 130
[[801  24]
 [ 66  61]]
0.9072297780959198
684 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 3
n_trees: 812
[[796  14]
 [ 65  77]]
0.9447574334898279
685 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 6
min_leaf: 1
n_trees: 717
[[821   6]
 [ 67  58]]
0.9359419588875453
686 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 4
n_trees: 643
[[804  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 2
min_leaf: 1
n_trees: 849
[[800  20]
 [ 80  52]]
0.9021433850702143
715 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 3
min_leaf: 1
n_trees: 821
[[815   8]
 [ 83  46]]
0.9234884662842502
716 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 4
n_trees: 778
[[798  18]
 [ 81  55]]
0.8860654555940023
717 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 9
min_leaf: 5
n_trees: 767
[[805  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 2
min_leaf: 1
n_trees: 334
[[811  11]
 [ 69  61]]
0.9247332959011791
746 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 2
n_trees: 164
[[809  10]
 [ 69  64]]
0.9219201850780797
747 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 2
min_leaf: 5
n_trees: 129
[[809  11]
 [ 80  52]]
0.9030672579453067
748 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 2
n_trees: 424
[[806  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 5
max_features: 6
min_leaf: 1
n_trees: 650
[[807  16]
 [ 76  53]]
0.9140316670905272
777 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 5
max_features: 9
min_leaf: 1
n_trees: 533
[[804  18]
 [ 80  50]]
0.8858693617817706
778 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 5
n_trees: 791
[[798  17]
 [ 81  56]]
0.9074739151851686
779 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 2
n_trees: 691
[[815  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 7
min_leaf: 5
n_trees: 303
[[801  15]
 [ 70  66]]
0.9356437427912341
808 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 2
min_leaf: 4
n_trees: 750
[[811   7]
 [ 91  43]]
0.9019541656023065
809 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 4
min_leaf: 5
n_trees: 729
[[814   9]
 [ 80  49]]
0.9121760999180537
810 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 5
min_leaf: 1
n_trees: 410
[[800  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 4
min_leaf: 2
n_trees: 867
[[811  14]
 [ 86  41]]
0.9100167024576473
839 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 3
n_trees: 929
[[810  13]
 [ 81  48]]
0.8926973541684329
840 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 8
min_leaf: 1
n_trees: 573
[[802  15]
 [ 74  61]]
0.9194433111201779
841 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 5
min_leaf: 3
n_trees: 452
[[807  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 4
min_leaf: 2
n_trees: 412
[[813  11]
 [ 77  51]]
0.9315837378640777
870 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 3
n_trees: 405
[[790  23]
 [ 72  67]]
0.9164211066571099
871 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 2
n_trees: 316
[[802  18]
 [ 75  57]]
0.9286770140428677
872 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 5
min_leaf: 1
n_trees: 674
[[812  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 1
n_trees: 371
[[796  23]
 [ 71  62]]
0.90670816234726
901 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 6
max_features: 7
min_leaf: 2
n_trees: 423
[[807  22]
 [ 70  53]]
0.9130404934929929
902 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 6
min_leaf: 5
n_trees: 414
[[808  13]
 [ 69  62]]
0.9177506485295348
903 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 2
min_leaf: 2
n_trees: 276
[[808  12

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 1
n_trees: 435
[[821   3]
 [ 80  48]]
0.9322474211165048
932 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 9
min_leaf: 1
n_trees: 153
[[810  19]
 [ 63  60]]
0.9039689311247756
933 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 4
min_leaf: 5
n_trees: 120
[[808  14]
 [ 72  58]]
0.9035841287666105
934 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 8
min_leaf: 1
n_trees: 549
[[818  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 5
min_leaf: 1
n_trees: 919
[[812  11]
 [ 64  65]]
0.9324648902201249
963 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 7
min_leaf: 3
n_trees: 388
[[802  20]
 [ 59  71]]
0.9109582631480442
964 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 5
n_trees: 715
[[803  11]
 [ 94  44]]
0.9094826051347791
965 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 3
n_trees: 759
[[807  

Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 2
min_leaf: 2
n_trees: 795
[[796  13]
 [ 90  53]]
0.9194464373697995
994 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 1
min_leaf: 1
n_trees: 381
[[814   8]
 [ 86  44]]
0.9196238068500843
995 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 7
max_features: 7
min_leaf: 1
n_trees: 660
[[801  18]
 [ 59  74]]
0.919762776905634
996 of 999
Running search 1 out of 5
Running search 2 out of 5
Running search 3 out of 5
Running search 4 out of 5
Running search 5 out of 5
The best hyperparameters were:
max_depth: 8
max_features: 3
min_leaf: 2
n_trees: 980
[[809  1